<?php
/**
 * Created by PhpStorm.
 * User: ruslanzh
 * Date: 12/08/16
 * Time: 10:57
 */

namespace common\components\debug;

use common\models\User;
use yii\bootstrap\Html;
use yii\debug\Panel;
use yii\helpers\VarDumper;

class userDebugPanel extends Panel
{
    public function getName()
    {
        return 'User';
    }

    public function getSummary()
    {
        $currentUser = \Yii::$app->user->identity;
        $html = Html::beginTag('div', ['class' => 'yii-debug-toolbar__block']);
        $link = 'Login: ';
        $link .= Html::tag('span', 'User: ' . $currentUser->username, ['class' => 'yii-debug-toolbar__label']);
        $link .= ' Role: ';
        $link .= Html::tag('span', User::getRoleName($currentUser->role), ['class' => 'yii-debug-toolbar__label yii-debug-toolbar__label_info']);
        $html .= Html::a($link, $this->getUrl());
        $html .= Html::endTag('div');

        return $html;
    }

    public function getDetail()
    {
        $html = '';

        VarDumper::dump(\Yii::$app->user->identity->attributes, 10 ,true);
        echo Html::tag('hr');
        VarDumper::dump(\Yii::$app->user, 10 ,true);

        return $html;
    }

    public function save()
    {
        parent::save();
    }

    public function load($data)
    {
        parent::load($data); // TODO: Change the autogenerated stub
    }

    public function getUrl()
    {
        return parent::getUrl(); // TODO: Change the autogenerated stub
    }

}